version: '3'

services:
  
  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - auth
    ports:
      - "5432:5432"
  
  statefull-auth-db:
    container_name: statefull-auth-db
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - auth
    ports:
      - "5433:5432"

  token-redis:
    container_name: token-redis
    image: redis:latest
    networks:
      - auth
    ports:
      - "6379:6379"


  stateless-auth-api:
    build: './Stateless/stateless-auth-api'
    container_name: stateless-auth-api
    depends_on:
      - stateless-auth-db
    environment:
      - PORT=8080
      - DB_HOST=stateless-auth-db
      - DB_PORT=5432
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - auth
    ports:
      - 8080:8080  

  stateless-any-api:
    build: './Stateless/stateless-any-api'
    container_name: stateless-any-api
    environment:
      - PORT=8081
    networks:
      - auth
    ports:
      - 8081:8081

  statefull-auth-api:
    build: './Statefull/statefull-auth-api'
    container_name: statefull-auth-api
    depends_on:
      - statefull-auth-db
    environment:
      - PORT=8082
      - DB_HOST=statefull-auth-db
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    networks:
      - auth
    ports:
      - 8082:8082

  statefull-any-api:
    build: './Statefull/statefull-any-api'
    container_name: statefull-any-api
    environment:
      - PORT=8083
    networks:
      - auth
    ports:
      - 8083:8083


networks:
  auth:
    driver: bridge